# backend/log_config.yaml

version: 1
disable_existing_loggers: False

formatters:
  # Formatter untuk log aplikasi (yang kita buat), sekarang kita beri nama 'default_color'
  default_color:
    (): "colorlog.ColoredFormatter"
    format: "%(log_color)s%(levelname)-8s%(reset)s | %(asctime)s | %(blue)s%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  # Formatter khusus untuk log akses Uvicorn, sekarang dengan timestamp
  access_color:
    (): "uvicorn.logging.AccessFormatter"
    # --- PERUBAHAN DI SINI: Tambahkan %(asctime)s ---
    fmt: '%(levelprefix)s| %(asctime)s |  %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: True

  # Formatter sederhana untuk file log (tetap sama)
  file_simple:
    format: "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  # Handler untuk log aplikasi di console
  default_console:
    class: "logging.StreamHandler"
    formatter: "default_color"
    stream: "ext://sys.stdout"

  # Handler untuk log akses di console
  access_console:
    class: "logging.StreamHandler"
    formatter: "access_color"
    stream: "ext://sys.stdout"

  # Handler untuk file (tetap sama)
  # file:
  #   class: "logging.handlers.RotatingFileHandler"
  #   formatter: "file_simple"
  #   filename: "logs/fotota_app.log"
  #   maxBytes: 10485760
  #   backupCount: 5
  #   encoding: utf8
  file:
    # Ganti class menjadi TimedRotatingFileHandler
    class: "logging.handlers.TimedRotatingFileHandler"
    formatter: "file_simple"
    
    # Ini adalah nama file log utama/saat ini
    filename: "logs/fotota_app.log"
    
    # Pengaturan untuk rotasi harian
    when: "midnight" # Rotasi setiap tengah malam
    interval: 1 # Intervalnya adalah 1 hari
    backupCount: 30 # Simpan log selama 30 hari ke belakang
    
    encoding: utf8
    # maxBytes tidak lagi diperlukan

# Konfigurasi logger utama aplikasi Anda
root:
  level: "INFO"
  handlers: ["default_console", "file"]

# Konfigurasi logger Uvicorn
loggers:
  uvicorn.error:
    level: "INFO"
    handlers: ["default_console", "file"] # Pakai handler default
    propagate: no
  uvicorn.access:
    level: "INFO"
    handlers: ["access_console", "file"] # Pakai handler akses khusus
    propagate: no